apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: react-nginx
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: react-nginx
  targetCPUUtilizationPercentage: 50
